name: GraalVM Native Image builds
on: [push]
jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: graalvm/setup-graalvm@v1
        with:
          version: "22.1.0"
          java-version: "11"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build main.java
        run: |
          cd server/src
          javac main.java
          native-image --static main

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: main-${{ matrix.os }}
          path: server/src/main*
