name: Spell Checker action
on: [pull_request, push]

jobs:
  run:
    name: Start Spell Checking with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v2

      - name: Check spelling of * Files
        uses: crate-ci/typos@master
        with:
          files: ./*
